groups:
 - name: infra.rule 
   rules:
     - alert: InstanceDown
       expr: up == 0
       for: 1m 
       labels: 
         severity: critical
       annotations:
         summary: "Target down"
         description: "Some scrape target is not responding"
     - alert: HighCPU
       expr: avg(rate(process_cpu_seconds_total[2m])) by (job) > 0.6
       for: 5m
       labels:
         severity: warning
       annotations:
       summary: "High CPU usage"
       description: "average CPU > 60% for 5m on job {{ $labels.job}}"
    
     - alert: HighLatency
       expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, job)) > 0.5
       for: 3m
       labels:
        severity: warning
       annotations:
        summary: "p95 latency > 500ms"
        description: "Service {{ $labels.job }} p95 > 500ms for 3m"
        