global:
resolve_timeout: 5m


route:
receiver: 'slack'
group_by: ['alertname']
group_wait: 10s
group_interval: 1m
repeat_interval: 1h


receivers:
- name: 'slack'
slack_configs:
- api_url: ${SLACK_WEBHOOK_URL}
channel: '#alerts'
send_resolved: true
title: '{{ .Status | toUpper }}: {{ .CommonLabels.alertname }}'
text: >-
*Labels:* {{ .CommonLabels }}\n*Annotations:* {{ .CommonAnnotations }}\n*StartsAt:* {{.Alert | first | .StartAt}}